DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
DESC VARCHAR(255)
);

INSERT INTO PRODUCTS VALUES(1, 'Lada', 'car');
INSERT INTO PRODUCTS VALUES(2, 'BMW', 'car');
INSERT INTO PRODUCTS VALUES(3, 'Toyota', 'car');
INSERT INTO PRODUCTS VALUES(4, 'SAAB', 'car');
INSERT INTO PRODUCTS VALUES(5, 'Nissan', 'car');
INSERT INTO PRODUCTS VALUES(6, 'Honda', 'car');
INSERT INTO PRODUCTS VALUES(7, 'Reno', 'car');

SELECT * FROM PRODUCTS
